# Generated by Django 5.1.1 on 2024-10-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no2_max', models.FloatField()),
                ('ozone_max', models.FloatField()),
                ('pm10_max', models.FloatField()),
                ('co2_min', models.FloatField(blank=True, null=True)),
                ('air_pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_value', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualityindex.aqiattributes')),
            ],
        ),
    ]
